### ISSUE TITLE
How to use this package

### ISSUE THREAD

**Issue by xiaochi-liu** [r-assist/errorist#6]
I just installed the errorist package and loaded it, getting a message that warnings and errors will automatically trigger a web search. However, when I execute an error code, even the "f( )" in the gif demonstration, it doesn't trigger a web search, no response. How should I check it?

**Comment by coatless** [comment]
@xiaochi-liu The package should just "work" out of the box. 

What happens when you type in _R_:

```r
getOption("error")
library(errorist)
getOption("error")
detach("package:errorist", unload = TRUE)
```

Also, are you attempting to load the package in `~/.Rprofile`? If so, RStudio will override the hook we setup. 

You should see the following workflow if everything is okay. 

```
library(errorist)
# Warnings and errors will automatically trigger a web search.
f()
# Error in f() : could not find function "f"
# Searching query in a web browser ... 

# Verify a handler was set
getOption("error")
# (function(query = geterrmessage(), rlang = TRUE) {

    if (!valid_query(query)) {
      message("`query` must contain only 1 element that is not empty.")
      return(invisible(""))
    }

    query = append_search_term_suffix(query, rlang, entry[["keywords"]][[keyword]])

    browse_url(entry$site_url, query, entry$suffix)
  })()

# Ensure the package restores output correctly.
detach("package:errorist", unload = TRUE)
# Warnings and errors are no longer automatically searched.
```

**Comment by coatless** [comment]
Outside of that, what happens when you type:

```r
utils::browseURL('https://news.google.com')
```

Does a web browser open? Or is a new tab added to your current browser?

**Comment by xiaochi-liu** [comment]
Many thanks for your response! Accroding to your suggestions, I get the following outcome:

``` r
getOption("error")
#> (function () 
#> invokeRestart("abort"))()

library(errorist)
#> Warnings and errors will automatically trigger a web search.

f()
#> Error in f(): could not find function "f"

getOption("error")
#> (function (query = geterrmessage(), rlang = TRUE) 
#> {
#>     if (!valid_query(query)) {
#>         message("`query` must contain only 1 element that is not empty.")
#>         return(invisible(""))
#>     }
#>     query = append_search_term_suffix(query, rlang, entry[["keywords"]][[keyword]])
#>     browse_url(entry$site_url, query, entry$suffix)
#> })()

detach("package:errorist", unload = TRUE)
#> Warnings and errors are no longer automatically searched.
```

In addition, when I type:
```r
utils::browseURL('https://news.google.com')
```
a new tab will add to my current browser, not a web browser open.

Looking forward to any suggestions. Thanks!

**Comment by xiaochi-liu** [comment]
And I don't quite understand how to load the package in `~/.Rprofile`.  I can't find this kind of file in my project...

**Comment by coatless** [comment]
@xiaochi-liu  I think for some reason _R_ is being run in a non-interactive state. What happens when you run:

```r
interactive()
```

I'm thinking this because:

```r
f()
#> Error in f(): could not find function "f"
```

Should have:

```r
f()
# Error in f() : could not find function "f"
# Searching query in a web browser ... 
```

The last part is only suppressed if _R_ is running non-interactively.

**Comment by xiaochi-liu** [comment]
@coatless Thanks for your advice. 

I'm writing the code in R Markdown, and this is kind of tricky. 

When I run `interactive()`, it indeed gives me a `TRUE`, just like the screenshot:
<img width="423" alt="Screen Shot 2020-02-09 at 11 03 01" src="https://user-images.githubusercontent.com/48895627/74093836-d3f5ce00-4b2b-11ea-8354-83950e84237d.png">

However, when I execute and rendered the `interactive()` command in `reprex()`, it shows the `FALSE`:
``` r
interactive()
#> [1] FALSE
```
<sup>Created on 2020-02-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This makes me pretty confused. Does the environment of R Markdown matter? 

And how should I change the interactivity of R? I tried `rlang::local_interactive(TRUE)` but it gave me "Error: Can't add an exit event at top-level".

**Comment by coatless** [comment]
So, `rmarkdown` evaluates code chunks differently than `.R` scripts. When _RMarkdown_ code chunks are run, the interactivity of the session is disabled. That is, `interactive()` returns `FALSE`. As a result, you'll have to use `errorist` with `.R` or console commands vs. `rmarkdown` notebooks.

**Comment by xiaochi-liu** [comment]
@coatless That's it. Thank you very much for your guidance.
